apiVersion: v1
kind: Service
metadata:
  name: apptest
  labels:
    app: apptest
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apptest
  type: LoadBalancer
