apiVersion: apps/v1
kind: Deployment
metadata:
  name: apptest
spec:
  selector:
    matchLabels:
      app: apptest
  replicas: 1
  template:
    metadata:
      labels:
        app: apptest
    spec:
      containers:
      - name: apptest
        image: desmondo1/webapp:18
        ports:
        - containerPort: 80
